spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/breadroll-education?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注入Mapper配置文件位置
  type-aliases-package: top.qiudb.pojo  #别名，同样为类名或者类名首字母小写  User => User|user
  configuration:
    mapUnderscoreToCamelCase: true  #数据库 字段下划线 转JAVA大写字母
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    top:
      qiudb:
        mapper: debug
