# 应用服务 WEB 访问端口
server:
  port: 8000
  servlet:
    session:
      timeout: 259200     # 单位 秒   60*60*24*3  3天发呆时间
    encoding:
      charset: utf-8
      force: true

# 应用名称
spring:
  application:
    name: breadroll-education

  profiles:
    include: redis,mail,jdbc,thymeleaf

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false

  servlet:
    multipart:
      max-file-size: 1023MB
      max-request-size: 1024MB
  mvc:
    static-path-pattern: /static/**

  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: true   #只能一个人登录 设为false
    # token风格
    token-style: uuid
    # 是否输出操作日志
    is-log: false
    # 打印版本字符画
    isV: true