spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1  # 112.126.92.148
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    # Redis 超时时间
    timeout: 10000
